### ISSUE TITLE
Make use of treeherder-client 3.0.0's connection pooling

### ISSUE THREAD

**Issue by edmorley** [mozilla/pulse_actions#105]
treeherder-client 3.0.0 now re-uses a requests session for the duration of that TreeherderClient instance.

If pulse_actions updated to 3.0.0 and refactored slightly, so that it re-used the same TreeherderClient for each client usage, you'd get a perf improvement from the HTTP keep-alives.

See here for more details:
https://bugzilla.mozilla.org/show_bug.cgi?id=1286240

**Comment by armenzg** [comment]
We picked up a new version of mozci that uses this.
