### ISSUE TITLE
Fix schema issues

### ISSUE THREAD

**Issue by armenzg** [mozilla/pulse_actions#77]
I had to revert to the latest release of mozci.
We're getting this error.

May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 New jobs requested by dhuang@mozilla.com for https://treeherder.mozilla.org/#/jobs?repo=try&revision=21c2dc7e426d80a6ab18397b6e215cbd2ba46ef9 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 List of builders: 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - OS X 10.7 try build 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - OS X 10.7 64-bit try leak test build 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-e10s-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-e10s-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-e10s-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-e10s-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-e10s-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-e10s-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-e10s-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-e10s-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-e10s-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-e10s-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-e10s-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-e10s-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-e10s-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Rev7 MacOSX Yosemite 10.10.5 try debug test mochitest-e10s-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - WINNT 5.2 try build 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - WINNT 5.2 try leak test build 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try opt test mochitest-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try opt test mochitest-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try opt test mochitest-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try opt test mochitest-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try opt test mochitest-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try opt test mochitest-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try opt test mochitest-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try debug test mochitest-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try debug test mochitest-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try debug test mochitest-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try debug test mochitest-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try debug test mochitest-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try debug test mochitest-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit try debug test mochitest-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-e10s-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-e10s-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-e10s-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-e10s-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-e10s-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-e10s-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try opt test mochitest-e10s-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try debug test mochitest-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try debug test mochitest-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try debug test mochitest-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try debug test mochitest-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try debug test mochitest-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try debug test mochitest-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 7 32-bit try debug test mochitest-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - WINNT 6.1 x86-64 try build 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - WINNT 6.1 x86-64 try leak test build 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try debug test mochitest-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try debug test mochitest-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try debug test mochitest-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try debug test mochitest-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try debug test mochitest-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try debug test mochitest-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try debug test mochitest-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-browser-chrome-5 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-e10s-browser-chrome-1 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-e10s-browser-chrome-2 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-e10s-browser-chrome-3 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-e10s-browser-chrome-4 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-e10s-browser-chrome-7 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-e10s-browser-chrome-6 
May 11 01:03:33 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows 8 64-bit try opt test mochitest-e10s-browser-chrome-5 
May 11 01:06:42 pulse-actions app/worker2.1: Traceback (most recent call last): 
May 11 01:06:42 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 75, in run_listener 
May 11 01:06:42 pulse-actions app/worker2.1:     consumer.listen() 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 151, in listen 
May 11 01:06:42 pulse-actions app/worker2.1:     self._drain_events_loop() 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 198, in _drain_events_loop 
May 11 01:06:42 pulse-actions app/worker2.1:     self.connection.drain_events(timeout=self.timeout) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events 
May 11 01:06:42 pulse-actions app/worker2.1:     return self.transport.drain_events(self.connection, **kwargs) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events 
May 11 01:06:42 pulse-actions app/worker2.1:     return connection.drain_events(**kwargs) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 326, in drain_events 
May 11 01:06:42 pulse-actions app/worker2.1:     return amqp_method(channel, args, content) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/channel.py", line 1909, in _basic_deliver 
May 11 01:06:42 pulse-actions app/worker2.1:     fun(msg) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 598, in _receive_callback 
May 11 01:06:42 pulse-actions app/worker2.1:     return on_m(message) if on_m else self.receive(decoded, message) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 564, in receive 
May 11 01:06:42 pulse-actions app/worker2.1:     [callback(body, message) for callback in callbacks] 
May 11 01:06:42 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 62, in handler_with_dry_run 
May 11 01:06:42 pulse-actions app/worker2.1:     route(data, message, dry_run) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 48, in route 
May 11 01:06:42 pulse-actions app/worker2.1:     treeherder_runnable.on_runnable_job_prod_event(data, message, dry_run) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 20, in on_runnable_job_prod_event 
May 11 01:06:42 pulse-actions app/worker2.1:     return on_runnable_job_event(data, message, dry_run, stage=False) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 110, in on_runnable_job_event 
May 11 01:06:42 pulse-actions app/worker2.1:     dry_run=dry_run) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/sources/buildbot_bridge.py", line 89, in schedule_graph 
May 11 01:06:42 pulse-actions app/worker2.1:     task_graph=task_graph, *args, **kwargs) 
May 11 01:06:42 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/taskcluster/tc.py", line 67, in schedule_graph 
May 11 01:06:42 pulse-actions app/worker2.1:     validate_schema(instance=task_graph, schema=TC_SCHEMA_URL) 
May 11 01:06:42 pulse-actions app/worker2.1: TypeError: validate_schema() got an unexpected keyword argument 'schema'

**Comment by martiansideofthemoon** [comment]
@armenzg we can close this I suppose

**Comment by armenzg** [comment]
Hopefully fixed with this new version of mozci:
https://github.com/mozilla/pulse_actions/commit/0c422c130cd6b8992dee9abb016f718880302914

Thanks for the fix!
