### ISSUE TITLE
Exclude "win8" talos jobs when we retrigger on completion of PGO builds 

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/pulse_actions#79]
ref #70 
So we added this feature and now we wish to exclude windows 8 jobs from this feature. @armenzg anything else needed here?

**Comment by armenzg** [comment]
This sounds about right; do you think you could tackle it?

**Comment by armenzg** [comment]
@jmaher we're tracking this in here.

**Comment by martiansideofthemoon** [comment]
@armenzg , I'll drop in a PR shortly. I think this should not be too difficult.
